### ISSUE TITLE
todolist  setup

### ISSUE THREAD

**Issue by ben-Run** [vincentzyc/vue3-demo#2]
TodoList.vue  
这里所有的代码都写在setup 里面，意义又是什么？ 能写一个对于setup 钩子，具体一点的使用场景吗？

**Comment by vincentzyc** [comment]
> TodoList.vue
> 这里所有的代码都写在setup 里面，意义又是什么？ 能写一个对于setup 钩子，具体一点的使用场景吗？

具体请看官网，本demo只是演示使用方法
